-- 트랜잭션
SELECT * FROM DEPT_TEMP;

--  데이터 정의어
CREATE TABLE MEMBER (
	EMAIL VARCHAR2(65),
	PASSWORD VARCHAR2(65),
	NAME VARCHAR2(45),
	AGE NUMBER(3),
	INTRO CLOB, -- 여러줄 텍스트 
	REG_DT DATE
);
--
--ALTER TABLE MEMBER ADD MOBILE VARCHAR2(15);
--
--ALTER TABLE MEMBER RENAME COLUMN MOBILE TO CELLPHONE;
--
--ALTER TABLE MEMBER DROP COLUMN CELLPHONE;
--
--ALTER TABLE MEMBER MODIFY NAME VARCHAR2(65);

RENAME MEMBER TO USER_INFO;

TRUNCATE TABLE EMP_TEMP;

--SELECT * FROM EMP_TEMP;
--
--DROP TABLE EMP_TEMP;
--
---- KEY
--SELECT * FROM DEPT;
--
--DELETE FROM DEPT WHERE DEPTNO=20;
--
--SELECT * FROM EMP WHERE DEPTNO=20;
--
--SELECT * FROM USER_CONSTRAINTS; -- 사전 테이블 제약조건이 담겨서 나옴

-- SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME ='EMP';

-- SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME ='EMP'; -- WHERER조건 범위를 지정


