-- 데이터를 추가, 수정, 삭제하는 데이터 조작어
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) 
VALUES (50, 'DTATBASE', 'INCHEON');

INSERT INTO DEPT_TEMP VALUES (60, 'WEB', 'INCHEON');
INSERT INTO DEPT_TEMP VALUES (70, 'WEB', NULL);
INSERT INTO DEPT_TEMP (DNAME, DEPTNO) VALUES('AI',80);


-- EMP_TEMP는 EMP의 구조로 복사 (테이터 X)
CREATE TABLE EMP_TEMP AS 
SELECT * FROM EMP WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP SELECT * FROM EMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, HIREDATE)
VALUES (9999, '이이름', 'CLERK', SYSDATE);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, HIREDATE)
VALUES (9998, '김이름', 'CLERK', '2024-10-02');

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, HIREDATE)
VALUES (9997, '최이름','CLERK', '2024/10/02');

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, HIREDATE)
VALUES (9996, '박이름','CLERK', TO_DATE('10/02/2024', 'MM/DD/YYYY'));


SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP 
	SET LOC = 'SEOUL'
WHERE DEPTNO =70; -- 70번 부서만 변경

DELETE FROM DEPT_TEMP;

DELETE FROM DEPT_TEMP WHERE LOC IS NULL;

SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP SET LOC='SEOUL'
WHERE DEPTNO = 60;

COMMIT;












