-- JOIN
SELECT  *  FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO; 

SELECT * FROM SALGRADE;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE FROM EMP E, SALGRADE s 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT 
	E1.EMPNO, E1.ENAME,
	E2.ENAME 관리자명,
	E2.JOB "관리자 직책"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

SELECT 
	D.*, E.ENAME 
FROM DEPT D, EMP E
WHERE  D.DEPTNO = E.DEPTNO(+); -- 왼쪽 외부 조인

SELECT E.ENAME, D.*
FROM EMP E, DEPT D WHERE E.DEPTNO(+) = D.DEPTNO;  -- 오른쪽 외부 조인


SELECT * FROM EMP NATURAL JOIN DEPT; -- 공통 컬럼한개



SELECT * FROM EMP JOIN DEPT USING(DEPTNO); -- 공통 컬럼 여러개

SELECT * FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO ; 

SELECT 
	D.*, E.ENAME
FROM DEPT D LEFT OUTER JOIN EMP E ON D.DEPTNO = E.DEPTNO;

SELECT 
	E.ENAME, D.*
FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


CREATE TABLE EMP2 AS SELECT * FROM EMP;


SELECT * FROM EMP2;

INSERT INTO EMP2 
	(EMPNO, ENAME, JOB, DEPTNO)
	VALUES (9999, '이이름', 'CLERK', 50);


SELECT 
	E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME 
FROM EMP2 E FULL OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


-- 서브 쿼리
SELECT 
	EMPNO, ENAME,
	(SELECT D. DNAME FROM DEPT D WHERE D.DEPTNO = E.DEPTNO) DNAME
FROM EMP E;





















