-- 참조무결성
DELETE FROM DEPT WHERE DEPTNO=20; -- 무결성 제약조건 위배


SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MEMBER'; -- NOT NULL 제약조건

DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	EMAIL VARCHAR2(65) CONSTRAINT NN_EMAIL NOT NULL,
	PASSWORD VARCHAR2(65) CONSTRAINT NN_PASSWORD NOT NULL,
	NAME VARCHAR2(45) CONSTRAINT NN_NAME NOT NULL,
	AGE NUMBER(3) CHECK(AGE >= 14),
	REG_DT DATE DEFAULT SYSDATE 
);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MEMBER';

DROP TABLE MEMBER;

INSERT INTO MEMBER VALUES ('USER01@test.org', '123456', '사용자011', SYSDATE); 
INSERT INTO MEMBER VALUES (NULL, '78901', '사용자02', SYSDATE);
INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, AGE)
VALUES ('user01@test.org', '123456', '사용자 01', 18);

SELECT * FROM "MEMBER" m ;

CREATE TABLE MEMBER (
	EMAIL VARCHAR2(65),
	PASSWORD VARCHAR2(65) CONSTRAINT NN_PASSWORD NOT NULL,
	NAME VARCHAR2(45) CONSTRAINT NN_NAME NOT NULL,
	REG_DT DATE
	PRIMARY KEY(EMAIL, NAME)
); 
-- 왜래키 

CREATE TABLE EMP_FK (
	EMPNO NUMBER (4) PRIMARY KEY,
	ENAME VARCHAR2(10) NOT NULL,
	JOB VARCHAR2(9) NOT NULL,
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2) REFERENCES DEPT (DEPTNO)
);








